cask_args appdir: "/Applications"
tap "neovim/neovim" || true

brew "awscli"
brew "bash"
brew "bash-completion2"
brew "direnv"
brew "docker"
brew "dos2unix"
brew "findutils"
brew "git"
brew "gnu-sed"
brew "gpg"
brew "moreutils"
brew "ncdu"
brew "neovim"
brew "nmap"
brew "node"
brew "rbenv"
brew "ruby-build"
brew "starship"
brew "stow"
brew "tree"
brew "wget"

cask "discord"
cask "firefox"
cask "ghostty"
cask "obsidian"
cask "raycast"
cask "signal"
cask "todoist-app"
cask "whatsapp"
